spring:
  datasource:
    url: jdbc:mysql://localhost:3306/productmanagement?useSSL=false&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: Gepoint
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
    date-format: yyyy-MM-dd
  # 数据库时间在前端页面上显示时减少一天的问题(解决格林时间和中部时间存在8小时时差造成的问题)
  jackson:
    default-property-inclusion: non_null
    date-format: "yyyy-MM-dd HH:mm:ss"
    time-zone: "GMT+8"
  # redis所在主机的IP地址
  redis:
    host: localhost
# mybatis配置文件以及sql
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
server:
 port: 8081